# Generated by Django 5.1.6 on 2025-02-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_dynamicform_name_employeerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.IntegerField()),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeeRecord',
        ),
    ]
